### ISSUE TITLE
misspelled boot logo correction and question?

### ISSUE THREAD

**Issue by vaultboy124** [crazysmile11012/robcoterminal#1]
I noticed that robco industries is misspelled and thought I could alert you to the misspelling.

I attempted to correct it on a fork but realized I have no freaking idea how to locate the issue or even fix it remotely. 

I kind of thought it would be an absolute ball-ache to update it after going through the effort of installing on a floppy diskette and then installing it on a computer that you would feel right at home using in the 80s considering the fact that it doesn't have a Wi-Fi nor ethernet connector as it is actually too old for it to properly work.
or I am too dumb to actually set up a home network for a proper trilobite computer.

also, question can this os support the data from five-inch floppy drives?
or is it only 3-inch drives that can be used with it?

**Comment by crazysmile11012** [comment]
thank you for making a issue! I will fix the spelling error in v0.0.4 also it runs on virtual box and due to the size it can't fit on a standard density 5 inch diskettes, i would highly recommend a IBM drive ribbon compatible 3 inch floppy (if you are on legacy / xt hardware) and i do note it will run on most x86 processors so it should just work, Also to address the networking concern it does support a isa (or pci/pcie) network card as long as you have the drivers handy (and hardware permits) i have tried my hand at it but all of my nic's don't have dos drivers and i can't find a isa nic for my ibm xt. 

NOTE: v0.0.4 will include drivers for cd's pre installed and configured, so you can load software to and from cd's (ide, sata) if you have a isa and external cd drive you can use that driver. i hope this answers your question vaultboy124 (nice name btw) cheers!

**Comment by crazysmile11012** [comment]
also in v0.0.4 i will include it as a iso image for computers with a cd or dvd drive don't have to convert

**Comment by vaultboy124** [comment]
my question was if the software could figure out how it could use data coming from the 5-inch drive correctly. 
not if it could boot from that form factor of diskette.

my computer is a dell 333d.
a kind of unknown IBM clone

it currently has a 3 inch and a 5-inch drive and a tape streamer for data backup but no cd drive. 

I am unsure if it will even support cd rom drives as the computer is from 1990. 

but what I do know is that this computer will only ever support ms-dos and nothing else as it might not be able to keep up with the data requirements of other windows versions 

if you wish you could look up dos drivers from the internet archive and somehow incorporate them into a second floppy to be installed later after the boot diskette

**Comment by crazysmile11012** [comment]
yes it can read data from that form factor, the functionality is baked into the kernel

**Comment by crazysmile11012** [comment]
the boot logo is fixed
